"""03_change_url_id

Revision ID: dd80106c37e1
Revises: 8866fd1400b8
Create Date: 2023-03-24 18:55:49.776238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd80106c37e1'
down_revision = '8866fd1400b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_column('url', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('key', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('url', 'id')
    # ### end Alembic commands ###
